version: "3"
services:
  webserver:
    build: ./
    container_name: pimcore_web
    ports:
      - "8082:80"
    depends_on:
      - mysql
      - redis
    volumes:
      - ./pimcore:/var/www/html
      - app-vendor:/var/www/html/vendor
      - app-cache:/var/www/html/var/cache
      - app-sessions:/var/www/html/var/sessions
      - app-versions:/var/www/html/var/versions
      - app-logs:/var/www/html/var/logs
  mysql:
    image: mysql:5.7
    container_name: pimcore_mysql
    ports:
      - "3308:3306"    
    environment:    
      MYSQL_ROOT_PASSWORD: 'root@docker'
      MYSQL_USER: 'root'
      MYSQL_PASS: 'root'
    volumes:
      - app-data:/var/lib/mysql
  redis:
    image: redis:5.0.6
    container_name: pimcore_redis
    ports:
      - "6380:6379"
volumes:
  app-data:
  app-vendor:
  app-cache:
  app-sessions:
  app-versions:
  app-logs:
