version: "3"
services:
  webserver:
    build: ./
    container_name: pimcore_web
    ports:
      - "8081:80"
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/var/www/html:cached
  mysql:
    image: mysql:5.7
    container_name: pimcore_mysql
    ports:
      - "3307:3306"    
    environment:    
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'root'
      MYSQL_PASS: 'root'
    volumes:
      - app-data:/var/lib/mysql
  redis:
    image: redis:5.0.6
    container_name: pimcore_redis
    ports:
      - "6380:6379"
volumes:
  app-data:
